name: sgt_projeto
description: Sistema de Gestão de Terrenos - CIG Investimento
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Versões atualizadas para evitar erros de compilação (Tecnologia de Ponta)
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.4
  file_picker: ^8.0.0
  provider: ^6.1.1
  google_fonts: ^6.2.1
  drag_and_drop_lists: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Garante que os ícones e imagens da web sejam incluídos
  assets:
    - web/icons/
    - web/favicon.png